import type { Metadata } from "next";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import GlobalLayout from "@repo/ui/GlobalLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-pretendard antialiased"
      >
        <GlobalLayout>
          {children}
        </GlobalLayout>
      </body>
    </html>
  );
}
